#!/bin/bash
printUsage(){
    echo 'smarthost <hosts> hosts file directory.'
}

if [[ $# -eq 1 ]];then
    hostspath=$1
fi

if [[ $OS == "UNIX" ]];then
    hostspath="/etc"
fi

if [[ $OS == "Windows_NT" ]];then
    hostspath="/cygdrive/c/Windows/System32/drivers/etc"
fi

if [[ $hostspath == "" ]];then
    printUsage;
fi

echo "hosts file's directory is "$hostspath
nohup wget --no-check-certificate https://smarthosts.googlecode.com/svn/trunk/hosts -O /tmp/hosts >>/dev/null 2>&1

cat /tmp/hosts |grep '#UPDATE' >>  $hostspath'/hosts.tmp'

sed -e '/#SmartHosts START/,/#SmartHosts END/d' -e '1,1d' $hostspath'/hosts' >> $hostspath'/hosts.tmp'

sed -n '/#SmartHosts START/,/#SmartHosts END/p' /tmp/hosts >> $hostspath'/hosts.tmp'

mv $hostspath'/hosts' $hostspath'/hosts.bak'
mv $hostspath'/hosts.tmp' $hostspath'/hosts'

echo 'update to '
head -n 1 $hostspath'/hosts'

rm -f /tmp/hosts 
